FROM openjdk:17.0.2

LABEL maintainer="Diego Flores <dfloresc1602@alumno.ipn.mx>"

WORKDIR /app

COPY ./target/eurekams-0.0.1-SNAPSHOT.jar .

EXPOSE 8761

ENTRYPOINT ["java","-jar","eurekams-0.0.1-SNAPSHOT.jar"]
